# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pic_folder/if_value_poster_2.png', upload_to='pic_folder/'),
        ),
    ]
